= Algorithms implemented using the NRW Informatik Abitur classes

A collection of algorithms implemented using the classes provided by the NRW Informatik Abitur.

== Sorting Algorithms

A collection of various sorting algorithms implemented using the classes provided by the NRW Informatik Abitur.

The following sorting algorithms are implemented:

* Insertion Sort
* Selection Sort
* Bubble Sort

== Search Algorithms

A collection of search algorithms implemented using the classes provided by the NRW Informatik Abitur.

The following search algorithms are implemented:

* Linear Search
* Binary Search

== Graph Algorithms

A collection of graph algorithms implemented using the classes provided by the NRW Informatik Abitur.

The following graph algorithms are implemented:

* Depth First Search
* Breadth First Search
* Dijkstra's Algorithm

== Tree Algorithms

A collection of tree algorithms implemented using the classes provided by the NRW Informatik Abitur.

The following tree algorithms are implemented:

* Preorder Traversal
* Inorder Traversal
* Postorder Traversal
* Number of Nodes
* Number of Nodes at a certain level
* Number of Leaves
* Number of Leaves at a certain level
* Height of Tree

=== Binary Search Tree

The following binary search tree algorithms are implemented:

* Get the smallest element
* Get the largest element
